In [13]:

arr = np.array([20,30,40,50,60])
print(f"Original array: {arr}")

Original array: [20 30 40 50 60]


In [15]:
# Basic array operations

print(f"Sum of array elements: {np.sum(arr)}")
print(f"Mean of array elements: {np.mean(arr)}")
print(f"Maximum element: {np.max(arr)}")
print(f"Minimum element: {np.min(arr)}")

Sum of array elements: 200
Mean of array elements: 40.0
Maximum element: 60
Minimum element: 20


In [16]:
# Create a 2D array

matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f"Original matrix:\n{matrix}")

Original matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [17]:
# Matrix operations

print(f"Sum of matrix elements: {np.sum(matrix)}")
print(f"Transpose of matrix:\n{matrix.T}")

Sum of matrix elements: 45
Transpose of matrix:
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [18]:
# Element-wise operations

arr_squared = arr ** 2
print(f"Array elements squared: {arr_squared}")

Array elements squared: [ 400  900 1600 2500 3600]


In [19]:
# Reshaping arrays

reshaped_arr = arr.reshape(5, 1)
print(f"Reshaped array (5x1):\n{reshaped_arr}")

Reshaped array (5x1):
[[20]
 [30]
 [40]
 [50]
 [60]]


In [20]:
# Using arange and linspace

range_arr = np.arange(0, 10, 2)
print(f"Array from arange: {range_arr}")

linspace_arr = np.linspace(0, 1, 5)
print(f"Array from linspace: {linspace_arr}")

Array from arange: [0 2 4 6 8]
Array from linspace: [0.   0.25 0.5  0.75 1.  ]
